name: b22_document_workspace_kmzm
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  get: 4.7.3
  flutter_screenutil: 5.9.3
  event_bus: 2.0.1
  get_storage: 2.1.1
  flutter_staggered_grid_view: 0.7.0
  pull_to_refresh: 2.0.0
  permission_handler: 12.0.3
  extended_tabs: 5.0.0
  share_plus: 12.0.1
  fluttertoast: 9.1.0
  doc_scan_flutter: 2.0.0
  webview_flutter: 4.13.1
  flutter_preview_file: 0.0.9
  app_settings: 6.1.1
  lottie: 3.3.0
  image_picker: 1.2.2
  firebase_remote_config: 6.5.3
  firebase_core: 4.11.0
  firebase_analytics: 12.4.3
  flutter_pdf_ad_plugins: 0.2.9
  flutter_tba_info: 0.0.9
  flutter_app_lifecycle: 0.0.3
  flutter_check_af_new: 0.0.2
  flutter_pdf_risk_control_plugins:
    path: /Users/chengmengyi/testbird/plugins/flutter_pdf_risk_control_plugins
  sqflite: 2.4.2
  dio: 5.8.0+1
  flutter_custom_facebook: 0.0.5
  flutter_boom_notification_plugins:
    path: /Users/chengmengyi/testbird/plugins/flutter_boom_notification_plugins
  flutter_add_widget_plugins:
    path: /Users/chengmengyi/testbird/plugins/flutter_add_widget_plugins
  url_launcher: 6.3.2
  visibility_detector: 0.4.0+2
  path_provider: 2.1.6
  device_info_plus: 12.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/b22_access_media_ydmf/b22_permission_guides_nmul/
    - assets/b22_brand_identity_hvdt/b22_document_badges_oqwu/
    - assets/b22_conversion_media_xzqz/b22_tool_actions_wwfr/
    - assets/b22_conversion_media_xzqz/b22_workflow_status_pjra/
    - assets/b22_demo_library_kfgc/b22_reference_documents_abdz/
    - assets/b22_engagement_media_aquq/b22_feedback_prompts_ptmx/
    - assets/b22_localization_media_vmzp/b22_language_guides_rnat/
    - assets/b22_localization_media_vmzp/b22_locale_flags_gxbm/
    - assets/b22_monetization_media_pgct/b22_native_ad_surfaces_fxri/
    - assets/b22_motion_sequences_qnev/b22_document_processing_plaj/
    - assets/b22_preview_media_dzro/b22_annotation_controls_kigz/
    - assets/b22_runtime_registry_mokl/b22_acquisition_rules_apvl/
    - assets/b22_runtime_registry_mokl/b22_advertising_rules_tnui/
    - assets/b22_runtime_registry_mokl/b22_notification_rules_ihsi/
    - assets/b22_shared_controls_ybsz/b22_common_actions_lskr/
    - assets/b22_shared_controls_ybsz/b22_navigation_actions_dmkw/
    - assets/b22_typography_pack_zdok/b22_anybody_family_uqqy/
    - assets/b22_widget_extension_media_btai/b22_widget_resources_csgz/
    - assets/b22_workspace_media_vwug/b22_home_shell_xfaq/
    - assets/b22_workspace_media_vwug/b22_library_actions_pxds/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: black
      fonts:
        - asset: assets/b22_typography_pack_zdok/b22_anybody_family_uqqy/b22_anybody_expanded_black_fkda.ttf
    - family: extra
      fonts:
        - asset: assets/b22_typography_pack_zdok/b22_anybody_family_uqqy/b22_anybody_expanded_extra_bold_ahnc.ttf
    - family: medium
      fonts:
        - asset: assets/b22_typography_pack_zdok/b22_anybody_family_uqqy/b22_anybody_expanded_medium_qidi.ttf
    - family: semi
      fonts:
        - asset: assets/b22_typography_pack_zdok/b22_anybody_family_uqqy/b22_anybody_expanded_semi_bold_cupa.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
