// ignore_for_file: constant_identifier_names

enum AdPlacement {
  pr_new_open,
  pr_open_cold,
  pr_open_hot,
  pr_open_noti,
  pr_open_pop,
  pr_open_file,
  pr_open_mediapop,
  pr_permission_open,
  pr_new_lan_nat,
  pr_main_banner1,
  pr_main_banner2,
  pr_main_banner3,
  pr_up_int,
  pr_down_int,
  pr_sc_pdf,
  pr_w_pdf,
  pr_img_pdf,
  pr_refresh,
  pr_readback,
  pr_exit_app,
  unload_1,
  unload_2,
  unload_nat1,
  pr_search_int,
  pr_read_int,
  pr_comment,
}
